### ISSUE TITLE
Plural localization not working

### ISSUE THREAD

**Issue by entropious** [Decybel07/L10n-swift#12]
Just installed this pod and tried plural localization via
`"eventCount".l10n(arg: count)`
Added this lines to Localizable.strings
```
"eventCount.one" = "%d event";
"eventCount.many" = "%d events";
"eventCount.other" = "%d events";
```
Traced code, self.bundle in this function is nil, so no resource is loaded
```
    private func resource(named resourceName: String?) -> ResourceContainer {
        let resourceName = (resourceName ?? "").isEmpty ? "Localizable" : resourceName!

        return self.resources[resourceName] ?? {
            let resource = ResourceContainer(bundle: self.bundle, name: resourceName)
            self.resources[resourceName] = resource
            return resource
        }()
    }
```
Version 5.1.0

**Comment by Decybel07** [comment]
Could you answer the following questions?
- [ ] Is the file in the `xyz.lproj` folder (e.g. `en.lproj`)?
- [ ] Is the file added to the project?
- [ ] Is the file added to the target?
- [ ] Is the language set is supported by this file?
- [ ] Do localization keys (not plural) for this file work correctly?

**Comment by entropious** [comment]
It's in base.lproj folder and every other string in this file works fine

**Comment by Decybel07** [comment]
Can you write what returns the following code?
```swift
debugPrint(L10n.shared)
```

**Comment by entropious** [comment]
Right now i can't test it, will answer tomorrow

**Comment by entropious** [comment]
```
L10n {
	Language: en
	Preferred language: en
	Supported languages: ["Base", "ru", "en"]
	Bundle: nil
}
```

**Comment by entropious** [comment]
In private func languageChanged(oldValue: String? = nil) you only looking for en.lproj, ignoring Base.lproj where actual localization is located

**Comment by Decybel07** [comment]
Yes you are right. As the language is set, files from this language are taken, while others are ignored.

A proposal to solve your problem:

1. Move all files from `base.lproj` to `en.lproj`
2. [Remove Base from the list of supported languages](https://github.com/Decybel07/L10n-swift/wiki/FAQ#how-to-remove-base-from-the-list-of-supported-languages)

**Comment by entropious** [comment]
Base localization is used for all languages not currently supported. If i set french language, base localization will be used. This is iOS default behaviour. So fallback to base localization if localization for current language is not found seems pretty reasonable to me.

**Comment by Decybel07** [comment]
For me, this is not a bug, this is intentional behavior. If the application supports French and user set French, then why should it display text in English?

**Comment by entropious** [comment]
If app supports french, than it would be found by language in fr.lproj. I'm talking about behaviour when {language}.lproj is not found.

**Comment by Decybel07** [comment]
If {language}.lproj is not found then
- This framework doesn't support this language.
- The language is not on the list of supported languages ( `L10n.supportedLanguages` )
- The default language will be preferred ( `L10n.preferredLanguage` )

**Comment by Tsarfolk** [comment]
From Apple documentation `For example, if you select English as the development language, Xcode inserts the resource file in the Base.lproj project folder but not the en.lproj folder because the resource is already in English.`. At the end of the page https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/InternationalizingYourUserInterface/InternationalizingYourUserInterface.html

**Comment by Decybel07** [comment]
You convinced me, I'm going to add support for "base internacionalization"

**Comment by Decybel07** [comment]
@entropious, @Tsarfolk 
Problem is solved, the base internationalization is added to the library.
