### ISSUE TITLE
Support l10n for header of the static table view

### ISSUE THREAD

**Issue by KosratDAhmad** [Decybel07/L10n-swift#13]
Please add IBInspectable for the header of the static table view for more info look at the following image

<img width="254" alt="screen shot 2018-05-22 at 02 08 35" src="https://user-images.githubusercontent.com/10336475/40349266-c54e0870-5dae-11e8-899f-bd226c230ec7.png">

**Comment by Decybel07** [comment]
I am sorry but it's impossible. The `UITableViewSection` class isn't defined as public, so I'm not able to create a extension to this class
