### ISSUE TITLE
problem example

### ISSUE THREAD

**Issue by thierryH91200** [Decybel07/L10n-swift#14]
i have a problem  with example

![capture d ecran 2018-05-23 13 32 46](https://user-images.githubusercontent.com/6251463/40421994-1506aac2-5e8e-11e8-9032-c9a6ce0a6982.jpg)

Value of type 'KOLocalizedCore' has no member 'isUpdateOutside'
Value of type 'KOLocalizedCore' has no member 'url'
Value of type 'KOLocalizedCore' has no member 'isEnabelDebug'

help me

**Comment by Decybel07** [comment]
I think that you are write to the wrong person. It’s not my library.
