### ISSUE TITLE
Language doesn't change in static variables.

### ISSUE THREAD

**Issue by uditha2233** [Decybel07/L10n-swift#15]
I have some static variables in a struct which are used to display error messages to users

```swift
struct AlertBody {

    static let SOMETHING_WRONG = "There was an error service in your request. Please try again from while".l10n()
    static let NO_NETWORK_ERROR = "No internet Connection found. Check your connection or try again.".l10n()
}
```
When I change the language, these static variables still give the message in previous language.
In order to get the messages in correct language I have to close and reopen the app.
But is there any other way to reload these static variables at the run time?

**Comment by Decybel07** [comment]
In your case you use static stored properties. It means this variable is create only when you first time call this variable.

## Solution: ##
You need use static computed properties like this:

```swift
struct AlertBody {

    static var SOMETHING_WRONG: String {
        return = "key.in.localizable.file".l10n()
    }
}
```

**Comment by uditha2233** [comment]
@Decybel07 Thanks for the response. This is working for me.
