### ISSUE TITLE
language not changing in storyboard

### ISSUE THREAD

**Issue by ibhavin** [Decybel07/L10n-swift#18]
## Short description of the issue.
I have two Issues:
1) While I am changing app language it is not changing language of storyboard. It only changes string which is hard coded in code.
2) While I Re-Run app it runs with default language not with previously selected language

## What did you expect to happen?

- Change language in storyboard
- Set language selected unless user select other language

## What happened instead?
- It changes language which is hard coded in code`("Ok".l10n())` not changing in storyboard. - Language changes to default language every time I rerun app  

  
## How to reproduces this problem?
Here what I am doing for changing language:
`L10n.shared.language = "fr"`
After `L10nLanguageChanged` notification fired I am relaunching storyboard
```
let delegate = (UIApplication.shared.delegate! as! AppDelegate)
let storyboard = UIStoryboard(name: "Main", bundle: nil)
delegate.window!.rootViewController! = storyboard.instantiateInitialViewController()!

```  
#### DebugDescription
```
{
	Language: fr
	Preferred language: en
	Supported languages: ["en", "fr", "pt-PT", "sw"]
	Bundles: [
		"/var/containers/Bundle/Application/E88839BF-E6FA-439F-A73A-F52B1A59DDBD/MyApp.app/fr.lproj",
		"/var/containers/Bundle/Application/E88839BF-E6FA-439F-A73A-F52B1A59DDBD/MyApp.app/Base.lproj"
	]
}
```

**L10n-swift version:** Swift 4.2

**Xcode version:** Xcode 10.2.1

**Swift version:** Swift 5

#### Platform(s):
  -  iOS

#### File format(s):
  - strings

#### Installation method:
  - CocoaPods

Note:
I have localized storyboard with other languages.
```
/* Class = "UILabel"; text = "Home"; ObjectID = "7D7-TL-I6S"; */
"7D7-TL-I6S.text" = "Accueil";
```
If I add text in `L10n Text` in `Attributes inspector` language changes works in storyboard.
Can I change language without assigning text (`L10n Text`) to every control? I have localized every text in Main.strings(French) for storyboard.

**Comment by Decybel07** [comment]
>  ## 1. While I am changing app language it is not changing language of storyboard. It only changes string which is hard coded in code.

Yes you'r right. Unfortunately, currently I can't do anything with it, but you can check similar issue #7 

> `L10n.shared.language = "fr"` this property don't reload views! It only sets language for future localization.
> 
> For reload all text you need to re-localization all the texts (using @IBOutlets) or you have to reload all visible controllers in your application. Look at [this example](https://github.com/Decybel07/L10n-swift/blob/master/Example/Example%20iOS/Scenes/RTL/RightToLeftViewController.swift).

>  ## 2. While I Re-Run app it runs with default language not with previously selected language

This library doesn't store the user's set language between application sessions. If you want to get this functionality, then on the side of your application you should take care of storing and restoring this language.

### Example

```swift
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(_: UIApplication, didFinishLaunchingWithOptions _: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        // restore
        if let language = UserDefaults.standard.string(forKey: "language") {
            L10n.shared.language = language
        }
        
        // store
        NotificationCenter.default.addObserver(forName: .L10nLanguageChanged, object: self, queue: nil) { _ in
            UserDefaults.standard.set(L10n.shared.language, forKey: "language")
        }
        
        return true
    }
}
```
