### ISSUE TITLE
Swift 5.0 Support

### ISSUE THREAD

**Issue by kbelter** [Decybel07/L10n-swift#19]
Can you update the library to Swift 5.0?

Let me know if you need help i could create PR and do it myself :)

**Comment by Decybel07** [comment]
Then please create PR but remember to keep compatibility with previous versions

**Comment by kbelter** [comment]
Hi there :)
Thanks for the response,
Regarding compatility you mean about xcode compatiblity?
or IOS compatibility?
Because if it’s xcode we should push this version to 5.0 and the people that have their projects in older versions, they should use another branch/commit.
So what i can do is basically update all the methods and the entire project basically to swift 5.0 and regarding the iOS systems i can leave them as it is right now.

Woulf that be okay for you? If so i will do that tomorrow :)

**Comment by Decybel07** [comment]
I mean compatibility with previous versions of swift.

**Comment by kbelter** [comment]
Hi there i saw that you merged it, can you publish that change to cocoapods? i'm trying to pod update but i don't see the changes yet.
Thanks and sorry for the troubles.

**Comment by Decybel07** [comment]
I have just published a new version. I had to make some changes to publish this version

**Comment by kbelter** [comment]
@Decybel07 Thank you so much for the quick response and for this amazing library :)
Have a great weekend!!
