### ISSUE TITLE
Info.plist localization support

### ISSUE THREAD

**Issue by z-mp** [Decybel07/L10n-swift#22]
Decybel07, thank you for sharing this awesome resource. Integration in Swift project is easy and well documented and it works perfectly well. 

Only one issue remains from my perspective - either the Info.plist localication is not well documented or localization for Info.plist is not supported.

Would you pls comment on how to get this working?

**Comment by Decybel07** [comment]
Thank you for your feedback.
Unfortunately I can't help you.  System messages are always in the system language, you cannot change it for these alerts
