### ISSUE TITLE
Line break are escaped in translated strings

### ISSUE THREAD

**Issue by Morniak** [Decybel07/L10n-swift#28]
With the string `Phone\nNumber` in the `.stringsdict`, I'm getting the following string `"Phone\\nNumber"` instead of `"Phone\nNumber"`.
  
#### DebugDescription
```
"L10n {\n\tLanguage: en\n\tPreferred language: en\n\tSupported languages: [\"en\"]\n\tBundles: [\n\t\t\"/var/containers/Bundle/Application/1E0B4F9F-2F20-4503-8108-2C06E1FEDBE7/Cruise.app/en.lproj\",\n\t\t\"/var/containers/Bundle/Application/1E0B4F9F-2F20-4503-8108-2C06E1FEDBE7/Cruise.app/Base.lproj\"\n\t]\n}"
```

**L10n-swift version:**
5.7.3

**Xcode version:**
Xcode 12.4
Build version 12D4e

**Swift version:**
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin19.6.0

#### Platform(s):
  - [x] iOS
  - [ ] watchOS
  - [ ] tvOS
  - [ ] macOS

#### File format(s):
  - [ ] strings
  - [x] stringsdict
  - [ ] plist
  - [ ] json

#### Installation method:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Swift Package Manager
  - [ ] Other (which ones)

**Comment by Decybel07** [comment]
This is not a bug.
The `stringsdict` file allows you to jump to a new line using the key combination (option + enter)
