### ISSUE TITLE
Not support Localization in custom Framework

### ISSUE THREAD

**Issue by zaidahmed2468** [Decybel07/L10n-swift#29]
It works on Japanese and Italian perfectly (without needs to restart the app). But it did not works on Arabic and French even after restarting the app it not works. Kindly help me.

**Comment by Decybel07** [comment]
Can you provide me with more information from the issue template?

**Comment by zaidahmed2468** [comment]
> Can you provide me with more information from the issue template?

It also works perfectly in simple Xcode project , but in framework it didn't localize french and arabic langauge.

**Comment by Decybel07** [comment]
Can you also copy and paste output from `print(L10n.shared.debugDescription)`. Without this or full project, I can't help you

**Comment by zaidahmed2468** [comment]
{
	Language: fr
	Preferred language: fr
	Supported languages: ["ja", "en", "ar-SA", "it", "fr"]
	Bundles: [
		"/var/containers/Bundle/Application/5D0EDA32-D714-4CF9-81F1-9C058845EA13/AbcFramework.app/fr.lproj",
		"/var/containers/Bundle/Application/5D0EDA32-D714-4CF9-81F1-9C058845EA13/AbcFramework.app/Base.lproj"
	]
}

**Comment by Decybel07** [comment]
1. Make sure you have all the languages selected for your localizable files.
<img width="262" alt="Zrzut ekranu 2021-05-3 o 07 01 58" src="https://user-images.githubusercontent.com/15947101/116842691-b358de80-abdd-11eb-9ad3-83d89b9b5473.png">

2.  Make sure if these directories are named according to this list of supported languages 
`["ja", "en", "ar-SA", "it", "fr"]`
<img width="232" alt="Zrzut ekranu 2021-05-3 o 07 02 17" src="https://user-images.githubusercontent.com/15947101/116842757-edc27b80-abdd-11eb-9364-ba144ab1e581.png">

3. Can you configure logger and check console output when you change language code.

**Comment by zaidahmed2468** [comment]
I have all the languages selected and dictionaries are named according to list of supported languages 
*Debug Description* after change language code
L10n {
	Language: ja
	Preferred language: fr
	Supported languages: ["ja", "en", "it", "ar-SA", "fr"]
	Bundles: [
		"/Users/zaidahmedios/Library/Developer/CoreSimulator/Devices/AE8647C4-F8A9-4AAA-94C0-76125F3DBF72/data/Containers/Bundle/Application/5A59DB0D-87C0-4ED1-85EE-997D8D2E99A3/AbcFramework.app/ja.lproj",
		"/Users/zaidahmedios/Library/Developer/CoreSimulator/Devices/AE8647C4-F8A9-4AAA-94C0-76125F3DBF72/data/Containers/Bundle/Application/5A59DB0D-87C0-4ED1-85EE-997D8D2E99A3/AbcFramework.app/Base.lproj"
	]
}

**Comment by Decybel07** [comment]
Can you provide me your project?

**Comment by zaidahmed2468** [comment]
Its confidencial product , I will make demo project and send you.

**Comment by Decybel07** [comment]
Ok, then I'm waiting for the demo project

**Comment by zaidahmed2468** [comment]
Strange behaviour happens , In my framework Japanese language localize fine , but when i made demo framework no language is localized inside framework.
This is [https://drive.google.com/drive/folders/10GMn8l_kvsycQvoFLh7ySfF1jdpYalPn?usp=sharing](link) of demo framework.

**Comment by Decybel07** [comment]
Ok, now I understand everything. `L10n.shared` use `Bandle.main`. Your framework uses a separate bundle.

You have two possible solutions to this problem:
- All translations will be defined in the final application
- You can create instantiate of `L10n` using your framework's bundle `L10n(bundle: , language: , configuration: )`

**Comment by zaidahmed2468** [comment]
Thanks for your guidance and time , can you please create an instantiate of L10n using your framework's bundle L10n(bundle: , language: , configuration: ) and add this in my demoProject.

**Comment by Decybel07** [comment]
1. Create extension in your Framework
```swift 
extension L10n {
    
    static let xyzShared: L10n = {
        let instance = L10n(bundle: Bundle(for: XyzFramework.self), language: L10n.shared.language, configuration: L10n.shared.configuration)
        NotificationCenter.default.addObserver(forName: .L10nLanguageChanged, object: L10n.shared, queue: .current) { notification in
            instance.language = (notification.userInfo?["newValue"] as? String) ?? L10n.shared.language
        }
        return instance
    }()
}
```
2. Wherever you want to localize text in this framework, you must pass this instance
```swift
textLabel.text = "some.localize.key".l10n(.xyzShared)
```

**Comment by zaidahmed2468** [comment]
Thank you very much

**Comment by zaidahmed2468** [comment]
Sorry for again bothering
In iOS Framework when I set Arabic language then language is changed to ar.
Its working fine but text orientation is not changes , it show default (LeftToRight)
But after killing app Its show correct orientation (RightToLeft)
