### ISSUE TITLE
IBInspectable with custom bundle

### ISSUE THREAD

**Issue by vkhadyka** [Decybel07/L10n-swift#31]
I use L10n-swift library for the project localization. <br>
My project receives localisation files from the backend as json and stores it to the separate bundle in project's Documents folder. <br>
And I have to load localizations from Documents to L10n. <br>

I know that L10n can be created as a new instance  and pass my bundle as parameter into init method, but IBInspectable extension won't work with the custom bundle, bcouz IBInspectable use shared singleton with default L10n initialization. <br> 
How can I load my Bundle to L10n.shared and use IBInspectable extension as Main bundle?

**Comment by Decybel07** [comment]
Unfortunately, this library does not yet support the solution you described.

But I can suggest a solution that will work:
1. Use the standard shared instance
2. Inject translations from your backend into this shared instance using:
```swift 
L10n.shared.inject(dictionary: [String: Any], into resource: String? = nil)
```

Remember to inject translations at:
- application startup
- changing language
- downloading translations from the backend

**Comment by Decybel07** [comment]
Unfortunately, this library does not yet support the solution you described.

But I can suggest a solution that will work:
1. Use the standard shared instance
2. Inject translations from your backend into this shared instance using:
```swift 
L10n.shared.inject(dictionary: [String: Any], into resource: String? = nil)
```

Remember to inject translations at:
- application startup
- changing language
- downloading translations from the backend
