### ISSUE TITLE
Plurals does not work

### ISSUE THREAD

**Issue by Arideno** [Decybel07/L10n-swift#32]
## Short description of the issue.

  Hi, I am using iOS 15. Tried both SPM and Pods. Firstly created "minutes_time.one" and "minutes_time.other" in Localizable.string in en.lproj. When I am trying to call "minutes_time".l10nPlural(1) there is an error **No exact matches in call to instance method 'l10nPlural'**. Then I've tried to do "minutes_time".l10nPlural(args: [1]), but then I've got "minutes_time.other" version instead of "minutes_time.one"

#### DebugDescription
```
L10n {
	Language: en
	Preferred language: en
	Supported languages: ["en"]
	Bundles: [
		"/var/containers/Bundle/Application/6353C86E-3F14-4D72-95DE-250F4628A4D1/.../en.lproj"
	]
}
```

**L10n-swift version:** 5.10

**Xcode version:** 13.2.1 `xcodebuild -version`

**Swift version:** 5.5.2 `swift -version`

#### Platform(s):
  - [x] iOS
  - [ ] watchOS
  - [ ] tvOS
  - [ ] macOS

#### File format(s):
  - [x] strings
  - [ ] stringsdict
  - [ ] plist
  - [ ] json

#### Installation method:
  - [x] CocoaPods
  - [ ] Carthage
  - [x] Swift Package Manager
  - [ ] Other (which ones)

**Comment by Decybel07** [comment]
Hi, I can't reproduce your bug, could you please share the project with this bug?

**Comment by Arideno** [comment]
Here: [TestI10n.zip](https://github.com/Decybel07/L10n-swift/files/8449234/TestI10n.zip)
<img width="662" alt="Screenshot 2022-04-08 at 9 43 20 AM" src="https://user-images.githubusercontent.com/35293936/162379384-8a0e65c3-4ecc-4d1b-937b-b3b8e6f4c6d5.png">

**Comment by Decybel07** [comment]
> No exact matches in call to instance method 'l10nPlural'

The above error has been fixed. The latest version `5.10.1` should now be available.

---

I also checked your test project, the plurals work fine

**Comment by Arideno** [comment]
Hi, just updated to 5.10.1. The error has been fixed. However, plurals does not work on test project on my computer. Both "number_of_apples".l10nPlural(1) and "number_of_apples".l10nPlural(2) returns "number_of_apples.other" version.
<img width="332" alt="Screenshot 2022-04-09 at 12 31 57 PM" src="https://user-images.githubusercontent.com/35293936/162566086-01e0642d-87e8-4a69-a5bf-8a059af30290.png">
<img width="347" alt="Screenshot 2022-04-09 at 12 32 07 PM" src="https://user-images.githubusercontent.com/35293936/162566094-48d344ab-6fc2-4383-a064-d571ebda170c.png">
<img width="54" alt="Screenshot 2022-04-09 at 12 32 16 PM" src="https://user-images.githubusercontent.com/35293936/162566099-e98f46d0-ba58-4a7d-b075-f689983e0c7a.png">

**Comment by Decybel07** [comment]
I have tried many times, however I am unable to reproduce your error. Your example project, regardless of configuration also works. 

1. Try to run tests on this library.
2. try to define plurals in Localizable.stringsdict

**Comment by Arideno** [comment]
I have tested a little bit. It does work on simulator, but on real device it does not...

**Comment by Arideno** [comment]
Figured it out, I have an error `Can't create file:///private/var/containers/Bundle/Application/F71F2D45-EEC2-4418-A56B-3FCD69545005/XXX.app/spmResources/Plural.stringsdict: You don’t have permission to save the file “spmResources” in the folder “XXX”.`

**Comment by Decybel07** [comment]
> Figured it out, I have an error `Can't create file:///private/var/containers/Bundle/Application/F71F2D45-EEC2-4418-A56B-3FCD69545005/XXX.app/spmResources/Plural.stringsdict: You don’t have permission to save the file “spmResources” in the folder “XXX”.`

This is very useful information. In the latest version `5.10.2` it should be fine
