### ISSUE TITLE
'L10n' is not a member type of class 'FrameworkMainClass.FrameworkMainClass'

### ISSUE THREAD

**Issue by zaidahmedpf** [Decybel07/L10n-swift#33]
I'm working on custom framework. I have created an xcframework file , when I import this file into demo project then I got this error. 
**'L10n' is not a member type of class 'FrameworkMainClass.FrameworkMainClass'**

**Comment by Decybel07** [comment]
I created a new framework which uses L10n and there is no problem.  Can you  proviede your project?
