### ISSUE TITLE
Get compilation error "Cannot convert value of type 'Int' to expected argument type 'L10n'"

### ISSUE THREAD

**Issue by gwynjudd** [Decybel07/L10n-swift#36]
## Short description of the issue.

I get this build error (but only on one machine):

![image](https://user-images.githubusercontent.com/314188/217122938-3e898ea8-3f15-440b-be47-8990baa928cd.png)

On a different machine, the identical code does not error and works just as expected.

The SupportConnectionError is defined thus:

![image](https://user-images.githubusercontent.com/314188/217123102-95a632e8-b31e-43d0-827c-d88ff7462384.png)

I found that on the machine on which the error is occurring, the Pods/Manifest.lock has got a different version for L10n-swift (the one without the error has 5.7.3) :

![image](https://user-images.githubusercontent.com/314188/217125526-d582b963-03f4-47d6-b898-7d35235a35ee.png)

Has there been a change between these two versions which would cause this error to occur?

## What did you expect to happen?

I expect it to build as expected without the error. Honestly I'm a bit stuck - I'm not really an expert on Swift, but it baffles me why this error is appearing only on one machine. Any ideas that can help would be appreciated.
  
## How to reproduces this problem?

It is hard to say. Like I said it only seems to happen on one particular machine.
  
## Environment.

The environment should be basically the same. Both are using xCode 14.2, and the code is built from the same source.

#### DebugDescription
```
Happy to do so if required? But since it is a build error, I don't know it would be relevant
```

**L10n-swift version:** 5.7.3 (works) 5.9.0 (errors)

**Xcode version:**

❯ xcodebuild -version
Xcode 14.2
Build version 14C1

**Swift version:** 

❯ swift -version
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: x86_64-apple-macosx12.

#### Platform(s):
  - [ ] iOS
  - [ ] watchOS
  - [ ] tvOS
  - [ ] macOS

#### File format(s):
  - [ ] strings
  - [ ] stringsdict
  - [ ] plist
  - [ ] json

#### Installation method:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Swift Package Manager
  - [ ] Other (which ones)

**Comment by gwynjudd** [comment]
Sorry I think I found the change - https://github.com/Decybel07/L10n-swift/commit/68a6aa8d8aa9706f0743cddc7d7995b38f209ad4

It seems like an intentional change:

![image](https://user-images.githubusercontent.com/314188/217126820-49f1cee8-660e-443e-b9f6-f8f8833b89c5.png)

Any suggestions on how to fix up my code?

**Comment by Decybel07** [comment]
Thank you for your Feedback.  You will find the solution below ;)

`"errorStatus".l10n(arg: status)`
