### ISSUE TITLE
AppleLanguages isn't updated in some conditions, leading to Apple UI Stock elements to show in the wrong language

### ISSUE THREAD

**Issue by AnthoPakPak** [Decybel07/L10n-swift#38]
## Short description of the issue.

I guess there is an issue in the `preferredLanguage` setter in `Bundle+utils.swift` where the `AppleLanguages` user default is not updated correctly if the preferred language is already the first item in the preferred languages list. It can happen if I set `L10n.shared.language` to another language than my `preferredLanguage`, then set it back to the `preferredLanguage`. This issue leads to Apple UI Stock elements to show in the wrong language (for example, an image picker).

## What did you expect to happen?

The `AppleLanguages` user default should be updated correctly, even if the new value is already the first item in the preferred languages list.

## What happened instead?

When setting `preferredLanguage` to a value that is already the first item in the list, the method returns early and does not update the `AppleLanguages` user default. This results in the previous language to remain first in the list.

## How to reproduce this problem?

1. Initial `preferredLanguages` as defined in my project is `["fr"]`
2. Call `preferredLanguage = "en"` (by setting `L10n.shared.language = "en"`)
3. `AppleLanguages` now contains `["en", "fr"]`
4. Call `preferredLanguage = "fr"` (by setting `L10n.shared.language = "fr"`)
5. `AppleLanguages` still contains `["en", "fr"]` because it hasn't been updated, whereas it should only contain `["fr"]`.
6. Notice that Apple UI Stock elements are showing up in English whereas they should show up in French.

## Suggested fix

I've fixed it by replacing [this check](https://github.com/Decybel07/L10n-swift/blob/813aa7229b7e32e2cc579055bdc6ac2195c72ff9/Source/Core/Extensions/Bundle%2Butils.swift#L28):

```
guard index > 0 else {
    return
}
```

to this:

```
guard index >= 0 else {
    return
}
```

Thanks to this, it doesn't return early and thus doesn't prevent `AppleLanguages` from being updated.

**Comment by Decybel07** [comment]
@AnthoPakPak Thank you for your feedback and suggestions. Sorry for the delay, but I have been on vacation. According to your suggestion, I corrected the condition in `guard` and more precisely I removed it (if there is an index it will always be greater than or equal to zero, so this `guard` was unnecessary).

**Comment by AnthoPakPak** [comment]
No worries! Thanks for fixing and updating it. Great work! 🤙
