### ISSUE TITLE
Change language and reload views

### ISSUE THREAD

**Issue by ControlAdad** [Decybel07/L10n-swift#7]
Settings this would not reload all views, what should I do?

`L10n.shared.language = "fa-IR"`

**Comment by Decybel07** [comment]
`L10n.shared.language = "fa-IR"` this property don't reload views! It only sets language for future localization.

For reload all text you need to re-localization all the texts (using @IBOutlets) or you have to reload all visible controllers in your application. Look at [this example](https://github.com/Decybel07/L10n-swift/blob/master/Example/Example%20iOS/Scenes/RTL/RightToLeftViewController.swift).
