### ISSUE TITLE
String.L10n() is not working

### ISSUE THREAD

**Issue by ControlAdad** [Decybel07/L10n-swift#8]
I added a Localizable.strings with 3 languages into project and included it in build phase.
This is english version of it:
```
/*
 strings.strings
 NavigationDrawerController
 
 Created by A.V.Ebrahimi on 4/21/17.
 Copyright © 2017 CosmicMind. All rights reserved.
 */
"AppName" = "Mallowin";

```

But now this is not working :
`toolbar.title="AppName".l10n()`

**Comment by Decybel07** [comment]
You added `Localizable.strings` but in file's header you have `strings.strings`. Can you check the file name?

**Comment by Dfmarulanda** [comment]
I have the exact same problem:

```swift
/* 
  Localization.strings
  Crowdswap

  Created by Daniel Marulanda on 12/28/18.
  Copyright © 2018 Crowdswap, Inc. All rights reserved.
*/

"waiting" = "Waiting for a swap since";
"candidate" = "We found a swap";
"done" = "Swap was completed";
"get" = "Get";
"giving" = "giving";
```

Then i just use
` "candidate".l10n()`
 but nothing happens and the app just add the "candidate" string to my label
