### ISSUE TITLE
Conformance with CVarArg

### ISSUE THREAD

**Issue by Sroka** [Decybel07/L10n-swift#9]
Hi,

First of all, thanks for this library. Of all the projects I checked this one seems to handle plurals and localizations the best. I guess it takes handling plurals in Polish to understand this pain :P 

I have some problems with String extension function. I try to call it as it is in examples:

`"view_edit_profile_photos_content_text".l10n(args: 10)`

For some reason XCode gives me following compile time exception:

> Cannot invoke 'l10n' with an argument list of '(args: Int)'

**Comment by KosratDAhmad** [comment]
Hi there 

How can I use args for strings, for example, I have the following example: 

Hell, %@ welcome back.

How this feature will be done with this library??

**Comment by Decybel07** [comment]
```swift
// First take the value of the translation for the key
let value = L10n.shared.string(for: "yourKey")

// Then use this value as a format to fill it with arguments
let filledValue = L10n.shared.string(format: value, args: ["KosratDAhmad"])
```
